repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
    -   id: clang-format
        args: [--style=file]

-   repo: local
    hooks:
    -   id: clang-tidy
        name: clang-tidy
        entry: /opt/homebrew/opt/llvm/bin/clang-tidy
        language: system
        files: \.cpp$
        types: [c, c++]

# Temporarily disabled pylint hook due to compatibility issues with Python 3.12
# -   repo: https://github.com/pre-commit/mirrors-pylint
#     rev: v2.17.4
#     hooks:
#     -   id: pylint

# Temporarily disabled flake8 hook due to compatibility issues with Python 3.12
# -   repo: https://github.com/pycqa/flake8
#     rev: 6.1.0
#     hooks:
#     -   id: flake8
